;;;; input_processor.lisp
;;;;
;;;; Maps raw symptom text to Prolog symptom tokens.
;;;;
;;; ──────────────────────────────────────────────────────────────────────────
;;; SECTION 1 — Immutable Data  (association lists used as hash-maps)
;;; ──────────────────────────────────────────────────────────────────────────

(defparameter *symptom-synonyms*
  ;; ("phrase the patient might say" . CANONICAL-PROLOG-ATOM)
  ;; Longest phrases first so multi word matches beat single word ones.
  '(
    ;; ── 4+ word phrases ─────────────────────────────────────────────────────
    ("shortness of breath"           . breathlessness)
    ("difficulty breathing"          . breathlessness)
    ("difficulty in breathing"       . breathlessness)
    ("can't catch breath"            . breathlessness)
    ("trouble catching breath"       . breathlessness)
    ("coughing up blood"             . blood_in_sputum)
    ("blood in stool"                . bloody_stool)
    ("blood in urine"                . burning_micturition)
    ("blood in sputum"               . blood_in_sputum)
    ("blood in pee"                  . burning_micturition)
    ("pain behind eyes"              . pain_behind_the_eyes)
    ("pain behind the eyes"          . pain_behind_the_eyes)
    ("loss of appetite"              . loss_of_appetite)
    ("loss of balance"               . loss_of_balance)
    ("loss of smell"                 . loss_of_smell)
    ("loss of memory"                . altered_sensorium)
    ("pins and needles"              . weakness_in_limbs)
    ("room is spinning"              . spinning_movements)
    ("world is spinning"             . spinning_movements)
    ("off balance"                   . loss_of_balance)
    ("feel off balance"              . loss_of_balance)
    ("can't keep balance"            . loss_of_balance)
    ("skin turning yellow"           . yellowish_skin)
    ("eyes turning yellow"           . yellowing_of_eyes)
    ("urine smells bad"              . foul_smell_of_urine)
    ("urine smells"                  . foul_smell_of_urine)
    ("pain during urination"         . burning_micturition)
    ("pain when peeing"              . burning_micturition)
    ("burning when peeing"           . burning_micturition)
    ("pain when urinating"           . burning_micturition)
    ("urge to urinate"               . continuous_feel_of_urine)
    ("feel need to urinate"          . continuous_feel_of_urine)
    ("stiff in morning"              . movement_stiffness)
    ("joints feel stiff"             . movement_stiffness)
    ("hard to move"                  . movement_stiffness)
    ("can't move properly"           . movement_stiffness)
    ("hard to think"                 . lack_of_concentration)
    ("brain fog"                     . lack_of_concentration)
    ("can't concentrate"             . lack_of_concentration)
    ("can't focus"                   . lack_of_concentration)
    ("memory loss"                   . altered_sensorium)
    ("trouble remembering"           . altered_sensorium)
    ("feel confused"                 . altered_sensorium)
    ("heart beating fast"            . fast_heart_rate)
    ("heart skipping beats"          . palpitations)
    ("lump in throat"                . swelled_lymph_nodes)
    ("lump in neck"                  . swelled_lymph_nodes)
    ("pain under ribs"               . abdominal_pain)
    ("burning in throat"             . acidity)
    ("burning in chest"              . acidity)
    ("acid in throat"                . acidity)
    ("taste of acid"                 . acidity)
    ("night sweats"                  . sweating)
    ("cold sweats"                   . sweating)
    ("always hungry"                 . excessive_hunger)
    ("always thirsty"                . dehydration)
    ("sores in mouth"                . ulcers_on_tongue)
    ("pain in back"                  . back_pain)
    ("pain in neck"                  . neck_pain)
    ("pain in chest"                 . chest_pain)
    ("pain in joints"                . joint_pain)
    ("pain in muscles"               . muscle_pain)
    ("pain in legs"                  . muscle_pain)
    ("pain in arms"                  . muscle_pain)
    ("sudden severe headache"        . sudden_severe_headache)
    ("thunderclap headache"          . sudden_severe_headache)
    ("lower back pain"               . back_pain)
    ("upper back pain"               . back_pain)
    ("frequent bowel movements"      . diarrhoea)
    ("loose bowel movements"         . diarrhoea)
    ("my stomach hurts"              . stomach_pain)
    ("my back hurts"                 . back_pain)
    ("my head hurts"                 . headache)
    ("my whole body"                 . muscle_pain)
    ("hurt all over"                 . muscle_pain)
    ("hurting all over"              . muscle_pain)
    ("aching all over"               . muscle_pain)
    ("whole body aches"              . muscle_pain)
    ("whole body hurts"              . muscle_pain)
    ("burning up with fever"         . high_fever)
    ("running a fever"               . high_fever)
    ("got a fever"                   . high_fever)
    ("feel really hot"               . high_fever)
    ("cant see properly"             . blurred_and_distorted_vision)
    ("hard to see"                   . blurred_and_distorted_vision)
    ("trouble talking"               . slurred_speech)
    ("cant talk properly"            . slurred_speech)
    ("words coming out wrong"        . slurred_speech)
    ("hard to talk"                  . slurred_speech)
    ("cant talk"                     . slurred_speech)
    ("speech is slurred"             . slurred_speech)
    ("cant eat anything"             . loss_of_appetite)
    ("dont want to eat"              . loss_of_appetite)
    ("no desire to eat"              . loss_of_appetite)
    ("cant keep food down"           . vomiting)
    ("keep throwing up"              . vomiting)
    ("been throwing up"              . vomiting)
    ("cant stop throwing up"         . vomiting)
    ("cant stop vomiting"            . vomiting)
    ("cant stop coughing"            . cough)
    ("coughing all the time"         . cough)
    ("pain in my back"               . back_pain)
    ("pain in my chest"              . chest_pain)
    ("pain in my neck"               . neck_pain)
    ("pain in my stomach"            . stomach_pain)
    ("pain in my head"               . headache)
    ("pain in my joints"             . joint_pain)
    ("pain in my legs"               . muscle_pain)
    ("pain in my arms"               . muscle_pain)
    ("feel like fainting"            . dizziness)
    ("about to pass out"             . dizziness)
    ("feel like passing out"         . dizziness)
    ("seeing stars"                  . dizziness)

    ;; ── 3-word phrases ──────────────────────────────────────────────────────
    ("high blood pressure"     . high_blood_pressure)
    ("blood pressure"          . high_blood_pressure)
    ("high fever"              . high_fever)
    ("mild fever"              . mild_fever)
    ("low grade fever"         . mild_fever)
    ("chest pain"              . chest_pain)
    ("chest hurts"             . chest_pain)
    ("chest ache"              . chest_pain)
    ("chest tightness"         . chest_pain)
    ("chest pressure"          . chest_pain)
    ("neck hurts"              . neck_pain)
    ("neck ache"               . neck_pain)
    ("arm hurts"               . muscle_pain)
    ("arm ache"                . muscle_pain)
    ("arm pain"                . muscle_pain)
    ("cant breathe"            . breathlessness)
    ("cant breath"             . breathlessness)
    ("cannot breathe"          . breathlessness)
    ("hard to breathe"         . breathlessness)
    ("trouble breathing"       . breathlessness)
    ("tight chest"             . chest_pain)
    ("joint pain"              . joint_pain)
    ("joint ache"              . joint_pain)
    ("joint stiffness"         . movement_stiffness)
    ("joint swelling"          . swelling_joints)
    ("swollen joint"           . swelling_joints)
    ("back pain"               . back_pain)
    ("neck pain"               . neck_pain)
    ("knee pain"               . knee_pain)
    ("hip pain"                . hip_joint_pain)
    ("stomach pain"            . stomach_pain)
    ("abdominal pain"          . abdominal_pain)
    ("muscle pain"             . muscle_pain)
    ("muscle ache"             . muscle_pain)
    ("muscle weakness"         . muscle_weakness)
    ("muscle wasting"          . muscle_wasting)
    ("muscle cramps"           . cramps)
    ("muscle spasms"           . cramps)
    ("leg cramps"              . cramps)
    ("weight loss"             . weight_loss)
    ("weight gain"             . weight_gain)
    ("fast heartbeat"          . fast_heart_rate)
    ("rapid heartbeat"         . fast_heart_rate)
    ("racing heart"            . fast_heart_rate)
    ("heart racing"            . fast_heart_rate)
    ("heart pounding"          . palpitations)
    ("heart fluttering"        . palpitations)
    ("heart skipping"          . palpitations)
    ("blurred vision"          . blurred_and_distorted_vision)
    ("distorted vision"        . blurred_and_distorted_vision)
    ("blurry vision"           . blurred_and_distorted_vision)
    ("vision problems"         . blurred_and_distorted_vision)
    ("skin rash"               . skin_rash)
    ("skin peeling"            . skin_peeling)
    ("skin eruptions"          . nodal_skin_eruptions)
    ("skin patches"            . dischromic_patches)
    ("red spots"               . red_spots_over_body)
    ("swollen glands"          . swelled_lymph_nodes)
    ("swollen joints"          . swelling_joints)
    ("swollen legs"            . swollen_legs)
    ("swollen eyes"            . puffy_face_and_eyes)
    ("swollen face"            . puffy_face_and_eyes)
    ("swollen ankles"          . swollen_legs)
    ("swollen stomach"         . swelling_of_stomach)
    ("swollen abdomen"         . swelling_of_stomach)
    ("swollen belly"           . swelling_of_stomach)
    ("puffy eyes"              . puffy_face_and_eyes)
    ("puffy face"              . puffy_face_and_eyes)
    ("burning urination"       . burning_micturition)
    ("painful urination"       . burning_micturition)
    ("frequent urination"      . polyuria)
    ("frequent peeing"         . polyuria)
    ("peeing a lot"            . polyuria)
    ("excessive thirst"        . dehydration)
    ("always thirsty"          . dehydration)
    ("dry mouth"               . dehydration)
    ("excessive hunger"        . excessive_hunger)
    ("watery eyes"             . watering_from_eyes)
    ("dry eyes"                . watering_from_eyes)
    ("eye discharge"           . watering_from_eyes)
    ("red eyes"                . redness_of_eyes)
    ("pink eye"                . redness_of_eyes)
    ("red eye"                 . redness_of_eyes)
    ("eye redness"             . redness_of_eyes)
    ("eye pain"                . redness_of_eyes)
    ("sore throat"             . throat_irritation)
    ("cold hands"              . cold_hands_and_feets)
    ("cold feet"               . cold_hands_and_feets)
    ("cold fingers"            . cold_hands_and_feets)
    ("cold toes"               . cold_hands_and_feets)
    ("cold extremities"        . cold_hands_and_feets)
    ("enlarged thyroid"        . enlarged_thyroid)
    ("thyroid swollen"         . enlarged_thyroid)
    ("brittle nails"           . brittle_nails)
    ("runny nose"              . runny_nose)
    ("stuffy nose"             . runny_nose)
    ("blocked nose"            . runny_nose)
    ("nasal congestion"        . runny_nose)
    ("stiff neck"              . stiff_neck)
    ("dark urine"              . dark_urine)
    ("smelly urine"            . foul_smell_of_urine)
    ("yellow urine"            . yellow_urine)
    ("yellow eyes"             . yellowing_of_eyes)
    ("yellow skin"             . yellowish_skin)
    ("yellowish skin"          . yellowish_skin)
    ("dark stool"              . bloody_stool)
    ("black stool"             . bloody_stool)
    ("rectal bleeding"         . bloody_stool)
    ("anal bleeding"           . bloody_stool)
    ("rectal pain"             . pain_in_anal_region)
    ("anal itch"               . irritation_in_anus)
    ("anal itching"            . irritation_in_anus)
    ("arm weakness"            . weakness_in_limbs)
    ("leg weakness"            . weakness_in_limbs)
    ("facial drooping"         . facial_drooping)
    ("face drooping"           . facial_drooping)
    ("slurred speech"          . slurred_speech)
    ("severe headache"         . sudden_severe_headache)
    ("morning stiffness"       . movement_stiffness)
    ("mood changes"            . mood_swings)
    ("sugar level"             . irregular_sugar_level)
    ("blood sugar"             . irregular_sugar_level)
    ("high sugar"              . irregular_sugar_level)
    ("varicose veins"          . prominent_veins_on_calf)
    ("bulging veins"           . prominent_veins_on_calf)
    ("spider veins"            . prominent_veins_on_calf)
    ("easy bruising"           . bruising)
    ("dry cough"               . cough)
    ("wet cough"               . phlegm)
    ("productive cough"        . phlegm)
    ("bloody phlegm"           . blood_in_sputum)
    ("bloody mucus"            . blood_in_sputum)
    ("sunken eyes"             . sunken_eyes)
    ("hollow eyes"             . sunken_eyes)
    ("body aches"              . muscle_pain)
    ("body pain"               . muscle_pain)
    ("aching all over"         . muscle_pain)
    ("sore muscles"            . muscle_pain)
    ("room spinning"           . spinning_movements)
    ("throwing up"             . vomiting)
    ("threw up"                . vomiting)
    ("loose stool"             . diarrhoea)
    ("loose stools"            . diarrhoea)
    ("poop so much"            . diarrhoea)
    ("pooping so much"         . diarrhoea)
    ("poop a lot"              . diarrhoea)
    ("pooping a lot"           . diarrhoea)
    ("going a lot"             . diarrhoea)
    ("cant poop"               . constipation)
    ("cannot poop"             . constipation)
    ("hard to poop"            . constipation)
    ("cannot go"               . constipation)
    ("cant go"                 . constipation)
    ("coughing blood"          . blood_in_sputum)
    ("spitting blood"          . blood_in_sputum)
    ("blood when coughing"     . blood_in_sputum)
    ("upset stomach"           . stomach_pain)
    ("stomach cramps"          . abdominal_pain)
    ("tummy pain"              . stomach_pain)
    ("belly pain"              . abdominal_pain)
    ("spinning sensation"      . spinning_movements)
    ("cold hands and feet"     . cold_hands_and_feets)
    ("hard to breathe"         . breathlessness)
    ("out of breath"           . breathlessness)
    ("short of breath"         . breathlessness)
    ("difficulty swallowing"   . throat_irritation)
    ("trouble swallowing"      . throat_irritation)
    ("pass out"                . dizziness)
    ("passed out"              . dizziness)
    ("feel faint"              . dizziness)
    ("going to faint"          . dizziness)
    ("no energy"               . fatigue)
    ("feel weak"               . fatigue)
    ("feel tired"              . fatigue)
    ("feel sick"               . nausea)
    ("feeling sick"            . nausea)
    ("feel nauseous"           . nausea)
    ("feel hot"                . high_fever)
    ("burning up"              . high_fever)
    ("back hurts"              . back_pain)
    ("back aching"             . back_pain)
    ("back aches"              . back_pain)
    ("stomach hurts"           . stomach_pain)
    ("tummy hurts"             . stomach_pain)
    ("belly hurts"             . abdominal_pain)
    ("head hurts"              . headache)
    ("head pounding"           . headache)
    ("no appetite"             . loss_of_appetite)
    ("not hungry"              . loss_of_appetite)
    ("cant eat"                . loss_of_appetite)
    ("mouth ulcers"            . ulcers_on_tongue)
    ("mouth sores"             . ulcers_on_tongue)
    ("sore mouth"              . ulcers_on_tongue)
    ("shoulder pain"           . muscle_pain)
    ("shoulder hurts"          . muscle_pain)
    ("shoulder ache"           . muscle_pain)
    ("seeing blurry"           . blurred_and_distorted_vision)
    ("cant walk"               . painful_walking)
    ("pain walking"            . painful_walking)
    ("walking hurts"           . painful_walking)
    ("speech problems"         . slurred_speech)
    ("trouble sleeping"        . restlessness)
    ("can not sleep"           . restlessness)
    ("cannot sleep"            . restlessness)

    ;; ── 1-word tokens ───────────────────────────────────────────────────────
    ("fever"                   . high_fever)
    ("feverish"                . high_fever)
    ("pyrexia"                 . high_fever)
    ("hyperthermia"            . high_fever)
    ("hypothermia"             . chills)
    ("temperature"             . mild_fever)
    ("cough"                   . cough)
    ("coughing"                . cough)
    ("wheezing"                . breathlessness)
    ("wheeze"                  . breathlessness)
    ("dyspnea"                 . breathlessness)
    ("dyspnoea"                . breathlessness)
    ("tachypnea"               . breathlessness)
    ("headache"                . headache)
    ("cephalgia"               . headache)
    ("migraine"                . headache)
    ("migraines"               . headache)
    ("nausea"                  . nausea)
    ("nauseated"               . nausea)
    ("vomiting"                . vomiting)
    ("vomit"                   . vomiting)
    ("vomited"                 . vomiting)
    ("puking"                  . vomiting)
    ("puke"                    . vomiting)
    ("diarrhea"                . diarrhoea)
    ("diarrhoea"               . diarrhoea)
    ("poop"                    . diarrhoea)
    ("pooping"                 . diarrhoea)
    ("blood"                   . blood_in_sputum)
    ("fatigue"                 . fatigue)
    ("tired"                   . fatigue)
    ("exhausted"               . fatigue)
    ("weakness"                . fatigue)
    ("pallor"                  . fatigue)
    ("pale"                    . fatigue)
    ("dizziness"               . dizziness)
    ("dizzy"                   . dizziness)
    ("lightheaded"             . dizziness)
    ("vertigo"                 . spinning_movements)
    ("spinning"                . spinning_movements)
    ("unsteady"                . loss_of_balance)
    ("wobbly"                  . loss_of_balance)
    ("chills"                  . chills)
    ("shivering"               . shivering)
    ("trembling"               . shivering)
    ("tremor"                  . shivering)
    ("tremors"                 . shivering)
    ("shaky"                   . shivering)
    ("sweating"                . sweating)
    ("sneezing"                . continuous_sneezing)
    ("congestion"              . runny_nose)
    ("congested"               . runny_nose)
    ("constipation"            . constipation)
    ("dehydration"             . dehydration)
    ("thirsty"                 . dehydration)
    ("anxiety"                 . anxiety)
    ("anxious"                 . anxiety)
    ("depression"              . depression)
    ("depressed"               . depression)
    ("sad"                     . depression)
    ("hopeless"                . depression)
    ("indigestion"             . indigestion)
    ("acidity"                 . acidity)
    ("heartburn"               . acidity)
    ("bloated"                 . swelling_of_stomach)
    ("bloating"                . indigestion)
    ("burping"                 . indigestion)
    ("belching"                . indigestion)
    ("flatulence"              . passage_of_gases)
    ("gas"                     . passage_of_gases)
    ("jaundice"                . yellowish_skin)
    ("jaundiced"               . yellowish_skin)
    ("icteric"                 . yellowish_skin)
    ("phlegm"                  . phlegm)
    ("mucus"                   . phlegm)
    ("palpitations"            . palpitations)
    ("palpitation"             . palpitations)
    ("tachycardia"             . fast_heart_rate)
    ("bradycardia"             . fast_heart_rate)
    ("bruising"                . bruising)
    ("cramps"                  . cramps)
    ("restlessness"            . restlessness)
    ("insomnia"                . restlessness)
    ("sleeplessness"           . restlessness)
    ("malaise"                 . malaise)
    ("unwell"                  . malaise)
    ("lethargy"                . lethargy)
    ("lethargic"               . lethargy)
    ("sluggish"                . lethargy)
    ("drowsy"                  . lethargy)
    ("drowsiness"              . lethargy)
    ("polyuria"                . polyuria)
    ("irritability"            . irritability)
    ("confused"                . altered_sensorium)
    ("disoriented"             . altered_sensorium)
    ("forgetful"               . altered_sensorium)
    ("paralysis"               . weakness_in_limbs)
    ("numbness"                . weakness_in_limbs)
    ("numb"                    . weakness_in_limbs)
    ("tingling"                . weakness_in_limbs)
    ("coma"                    . coma)
    ("blister"                 . blister)
    ("blackheads"              . blackheads)
    ("acne"                    . pus_filled_pimples)
    ("pimples"                 . pus_filled_pimples)
    ("rash"                    . skin_rash)
    ("hives"                   . skin_rash)
    ("welts"                   . skin_rash)
    ("itching"                 . itching)
    ("itchy"                   . itching)
    ("pruritus"                . itching)
    ("hoarse"                  . throat_irritation)
    ("hoarseness"              . throat_irritation)
    ("moody"                   . mood_swings)
    ("goiter"                  . enlarged_thyroid)
    ("edema"                   . swollen_legs)
    ("oedema"                  . swollen_legs)
    ("hemoptysis"              . blood_in_sputum)
    ("haemoptysis"             . blood_in_sputum)
    ("hematuria"               . burning_micturition)
    ("haematuria"              . burning_micturition)
    ("melena"                  . bloody_stool)
    ("haematochezia"           . bloody_stool)
    ("epistaxis"               . blood_in_sputum)
    ("dysuria"                 . burning_micturition)
    ("myalgia"                 . muscle_pain)
    ("arthralgia"              . joint_pain)
    ("hypertension"            . high_blood_pressure)
    ("cyanosis"                . breathlessness)))


;; Diagnostic weights: higher = more discriminating for a specific disease.
;; Python loads these via dump-weights.
(defparameter *symptom-weights*
  '((high_fever                      . 7)
    (chest_pain                      . 7)
    (weakness_in_limbs               . 7)
    (swelling_of_stomach             . 7)
    (coma                            . 7)
    (burning_micturition             . 6)
    (diarrhoea                       . 6)
    (patches_in_throat               . 6)
    (malaise                         . 6)
    (swelled_lymph_nodes             . 6)
    (stomach_bleeding                . 6)
    (spinning_movements              . 6)
    (enlarged_thyroid                . 6)
    (prominent_veins_on_calf         . 6)
    (pain_in_anal_region             . 6)
    (irritation_in_anus              . 6)
    (continuous_feel_of_urine        . 6)
    (blood_in_sputum                 . 5)
    (vomiting                        . 5)
    (stomach_pain                    . 5)
    (shivering                       . 5)
    (restlessness                    . 5)
    (cold_hands_and_feets            . 5)
    (nausea                          . 5)
    (indigestion                     . 5)
    (runny_nose                      . 5)
    (fast_heart_rate                 . 5)
    (phlegm                          . 5)
    (swollen_legs                    . 5)
    (swelling_joints                 . 5)
    (neck_pain                       . 5)
    (blurred_and_distorted_vision    . 5)
    (mild_fever                      . 5)
    (irregular_sugar_level           . 5)
    (redness_of_eyes                 . 5)
    (movement_stiffness              . 5)
    (passage_of_gases                . 5)
    (foul_smell_of_urine             . 5)
    (extra_marital_contacts          . 5)
    (history_of_alcohol_consumption  . 5)
    (breathlessness                  . 4)
    (fatigue                         . 4)
    (cough                           . 4)
    (dehydration                     . 4)
    (dark_urine                      . 4)
    (loss_of_appetite                . 4)
    (constipation                    . 4)
    (abdominal_pain                  . 4)
    (dizziness                       . 4)
    (stiff_neck                      . 4)
    (watering_from_eyes              . 4)
    (polyuria                        . 4)
    (palpitations                    . 4)
    (blister                         . 4)
    (anxiety                         . 4)
    (throat_irritation               . 4)
    (internal_itching                . 4)
    (continuous_sneezing             . 4)
    (nodal_skin_eruptions            . 4)
    (loss_of_balance                 . 4)
    (unsteadiness                    . 4)
    (bladder_discomfort              . 4)
    (mucoid_sputum                   . 4)
    (slurred_speech                  . 4)
    (cramps                          . 4)
    (bruising                        . 4)
    (obesity                         . 4)
    (excessive_hunger                . 4)
    (pain_behind_the_eyes            . 4)
    (yellowing_of_eyes               . 4)
    (yellow_urine                    . 4)
    (headache                        . 3)
    (yellowish_skin                  . 3)
    (back_pain                       . 3)
    (skin_rash                       . 3)
    (chills                          . 3)
    (acidity                         . 3)
    (muscle_wasting                  . 3)
    (weight_gain                     . 3)
    (mood_swings                     . 3)
    (weight_loss                     . 3)
    (sweating                        . 3)
    (depression                      . 3)
    (red_spots_over_body             . 3)
    (skin_peeling                    . 3)
    (lack_of_concentration           . 3)
    (yellow_crust_ooze               . 3)
    (knee_pain                       . 3)
    (joint_pain                      . 3)
    (lethargy                        . 2)
    (irritability                    . 2)
    (muscle_pain                     . 2)
    (altered_sensorium               . 2)
    (hip_joint_pain                  . 2)
    (muscle_weakness                 . 2)
    (receiving_unsterile_injections  . 2)
    (pus_filled_pimples              . 2)
    (blackheads                      . 2)
    (scurring                        . 2)
    (silver_like_dusting             . 2)
    (small_dents_in_nails            . 2)
    (inflammatory_nails              . 2)
    (red_sore_around_nose            . 2)
    (painful_walking                 . 2)
    (itching                         . 1)))

;; Affirmative responses recognised by normalize-response
(defparameter *yes-tokens*
  '("yes" "y" "yeah" "yep" "yup" "sure" "true" "absolutely" "definitely" "1" "correct" "right" "affirmative" "certainly" "of course" "indeed" "exactly" "you bet" "roger that" "aye" "uh-huh" "ok" "okay" "alright" "fine" "sounds good" "looks good" "works for me" "i agree" "i do" "i will" "i can" "i am in" "count me in" "sign me up" "let's do it" "let us do it" "go ahead" "proceed" "carry on" "continue" "by all means" "gladly" "willingly" "with pleasure" "certainly yes" "definitely yes" "absolutely yes " "of course yes" "indeed yes" "exactly yes" "you bet yes" "roger that yes" "aye yes" "uh-huh yes" "ok yes" "okay yes" "alright yes" "fine yes" "sounds good yes" "looks good yes" "works for me yes" "i agree yes" "i do yes" "i will yes" "i can yes" "i am in yes" "count me in yes" "sign me up yes" "let's do it yes" "let us do it yes" "go ahead yes" "proceed yes" "carry on yes" "continue yes" "by all means yes" "gladly yes" "willingly yes" "with pleasure yes"))


;;; ──────────────────────────────────────────────────────────────────────────
;;; SECTION 2 — Utility functions
;;; ──────────────────────────────────────────────────────────────────────────

;; Lowercase and strip apostrophes so can't→cant, don't→dont, etc.
(defun normalize-string (s)
  (map 'string
       (lambda (ch)
         (if (or (alphanumericp ch) (char= ch #\Space))
             ch
             #\Space))
       (remove #\' (string-downcase s))))

(defparameter *negation-tokens*
  '("no" "not" "dont" "doesn't" "doesnt" "without" "never"
    "cant" "cannot" "haven't" "havent" "hasn't" "hasnt"
    "denies" "denied" "absent" "absence" "nor" "nothing" "nowhere" "neither" "nonexistent" "refuses" "refused" "negative" "negative for" "negative to" "negative on" "negative in" "negative with" "negative without" "negative history of" "negative contact with" "negative exposure to" "negative travel history to" "negative family history of" "no history of" "no contact with" "no exposure to" "no travel history to" "no family history of" "denies history of" "denies contact with" "denies exposure to" "denies travel history to" "denies family history of" "without history of" "without contact with" "without exposure to" "without travel history to" "without family history of" "never had" "never had any" "never had a" "never had any history of" "never had a history of" "never had any contact with" "never had a contact with" "never had any exposure to" "never had a exposure to" "never had any travel history to" "never had a travel history to" "never had any family history of" "never had a family history of"))

;; After each negation token, skip the next WINDOW words.
;; "or" resets the skip so alternatives after "can't X or Y" are still captured.
(defun strip-negation-window (words &optional (window 3))
  (loop
    with result = '()
    with skip   = 0
    for w in words
    do (cond
         ((and (> skip 0) (string= w "or"))
          (setf skip 0))
         ((> skip 0)
          (decf skip))
         ((member w *negation-tokens* :test #'string=)
          (setf skip window))
         (t
          (push w result)))
    finally (return (nreverse result))))

;; Strip negated phrases from S before symptom extraction.
(defun remove-negations (s)
  (join-words (strip-negation-window (split-on-whitespace s))))

;; Tokenize S into whitespace delimited words.
(defun split-on-whitespace (s)
  (loop
    with result = '()
    with buf    = (make-array 0 :element-type 'character :adjustable t :fill-pointer 0)
    for ch across s
    do (if (char= ch #\Space)
           (when (> (length buf) 0)
             (push (copy-seq buf) result)
             (setf (fill-pointer buf) 0))
           (vector-push-extend ch buf))
    finally
      (when (> (length buf) 0)
        (push (copy-seq buf) result))
      (return (nreverse result))))

;; Join a list of strings with a single space.
(defun join-words (words)
  (if (null words)
      ""
      (reduce (lambda (a b) (concatenate 'string a " " b)) words)))

;; Return the canonical symbol for PHRASE from SYNONYMS alist, or NIL.
(defun lookup-synonym (phrase synonyms)
  (cdr (assoc phrase synonyms :test #'string=)))

;; Return the diagnostic weight of SYMPTOM from WEIGHTS alist (default 3).
(defun lookup-weight (symptom weights)
  (or (cdr (assoc symptom weights)) 3))


;;; ──────────────────────────────────────────────────────────────────────────
;;; SECTION 3 — N-gram generation
;;; ──────────────────────────────────────────────────────────────────────────

;; Return the first N elements of LST.
(defun take (n lst)
  (when (and lst (> n 0))
    (cons (car lst) (take (- n 1) (cdr lst)))))

;; Generate all n-grams of length N from WORDS.
(defun n-grams (words n)
  (when (>= (length words) n)
    (cons (join-words (take n words))
          (n-grams (cdr words) n))))

;; Return 3-, 2-, and 1-grams from WORDS. Longer phrases come first for matching.
(defun extract-all-phrases (words)
  (append (n-grams words 3)
          (n-grams words 2)
          (n-grams words 1)))


;;; ──────────────────────────────────────────────────────────────────────────
;;; SECTION 4 — Public pipeline functions
;;; ──────────────────────────────────────────────────────────────────────────

;; Free-text string -> list of canonical symptom symbols.
;; Steps: normalize -> strip negations -> tokenize -> n-grams -> synonym lookup -> dedup.
(defun extract-symptoms (raw-input)
  (let* ((normalized (normalize-string raw-input))
         (deneg      (remove-negations normalized))
         (words      (split-on-whitespace deneg))
         (phrases    (extract-all-phrases words))
         (mapped     (mapcar (lambda (p) (lookup-synonym p *symptom-synonyms*))
                             phrases))
         (found      (remove nil mapped)))
    (remove-duplicates found :from-end nil)))


;; Return the diagnostic weight of SYMPTOM (default 3).
(defun get-weight (symptom)
  (lookup-weight symptom *symptom-weights*))

;; Return an alist of (SYMPTOM . WEIGHT) pairs.
(defun weight-symptoms (symptoms)
  (mapcar (lambda (s) (cons s (get-weight s))) symptoms))

;; Sort SYMPTOMS by descending weight so high-yield ones get asked first.
(defun prioritize-symptoms (symptoms)
  (sort (copy-list symptoms) #'> :key #'get-weight))

;; Sum of diagnostic weights across all confirmed symptoms.
(defun severity-score (confirmed-symptoms)
  (reduce #'+ confirmed-symptoms :key #'get-weight :initial-value 0))

;; Remove from CANDIDATES any symptom in ALREADY-ASKED.
(defun filter-unasked (candidates already-asked)
  (remove-if (lambda (s) (member s already-asked)) candidates))

;; Return T if RESPONSE is an affirmative word, NIL otherwise.
(defun normalize-response (response)
  (member (normalize-string response) *yes-tokens* :test #'string=))


;;; ──────────────────────────────────────────────────────────────────────────
;;; SECTION 5 — Serialisation (output for Python bridge)
;;; ──────────────────────────────────────────────────────────────────────────

;; Serialise a symptom list to a space-separated lowercase string.
(defun symptoms-to-string (symptoms)
  (join-words
    (mapcar (lambda (s) (string-downcase (symbol-name s))) symptoms)))


;; Write all symptom weights to stdout as "symptom weight" lines for Python to load.
(defun dump-weights ()
  (dolist (pair *symptom-weights*)
    (format t "~a ~a~%" (string-downcase (symbol-name (car pair))) (cdr pair))))


;; Extract and prioritise symptoms from RAW-INPUT, then write them to stdout.
(defun process-input-for-bridge (raw-input)
  (let* ((syms        (extract-symptoms raw-input))
         (prioritized (prioritize-symptoms syms))
         (output      (symptoms-to-string prioritized)))
    (format t "~a~%" output)))

;; Read one line from stdin and run the extraction pipeline.
(defun run-from-stdin ()
  (let ((line (read-line *standard-input* nil "")))
    (process-input-for-bridge line)))
