% -----------------------------
% Precaution knowledge base
% -----------------------------

precaution(drug_reaction, stop_irritation).
precaution(drug_reaction, consult_nearest_hospital).
precaution(drug_reaction, stop_taking_drug).
precaution(drug_reaction, follow_up).
precaution(malaria, consult_nearest_hospital).
precaution(malaria, avoid_oily_food).
precaution(malaria, avoid_non_veg_food).
precaution(malaria, keep_mosquitos_out).
precaution(allergy, apply_calamine).
precaution(allergy, cover_area_with_bandage).
precaution(allergy, use_ice_to_compress_itching).
precaution(hypothyroidism, reduce_stress).
precaution(hypothyroidism, exercise).
precaution(hypothyroidism, eat_healthy).
precaution(hypothyroidism, get_proper_sleep).
precaution(psoriasis, wash_hands_with_warm_soapy_water).
precaution(psoriasis, stop_bleeding_using_pressure).
precaution(psoriasis, consult_doctor).
precaution(psoriasis, salt_baths).
precaution(gerd, avoid_fatty_spicy_food).
precaution(gerd, avoid_lying_down_after_eating).
precaution(gerd, maintain_healthy_weight).
precaution(gerd, exercise).
precaution(chronic_cholestasis, cold_baths).
precaution(chronic_cholestasis, anti_itch_medicine).
precaution(chronic_cholestasis, consult_doctor).
precaution(chronic_cholestasis, eat_healthy).
precaution(hepatitis_a, consult_nearest_hospital).
precaution(hepatitis_a, wash_hands_through).
precaution(hepatitis_a, avoid_fatty_spicy_food).
precaution(hepatitis_a, medication).
precaution(osteoarthristis, acetaminophen).
precaution(osteoarthristis, consult_nearest_hospital).
precaution(osteoarthristis, follow_up).
precaution(osteoarthristis, salt_baths).
precaution(vertigo_paroxysmal_positional_vertigo, lie_down).
precaution(vertigo_paroxysmal_positional_vertigo, avoid_sudden_change_in_body).
precaution(vertigo_paroxysmal_positional_vertigo, avoid_abrupt_head_movment).
precaution(vertigo_paroxysmal_positional_vertigo, relax).
precaution(hypoglycemia, lie_down_on_side).
precaution(hypoglycemia, check_in_pulse).
precaution(hypoglycemia, drink_sugary_drinks).
precaution(hypoglycemia, consult_doctor).
precaution(acne, bath_twice).
precaution(acne, avoid_fatty_spicy_food).
precaution(acne, drink_plenty_of_water).
precaution(acne, avoid_too_many_products).
precaution(diabetes, have_balanced_diet).
precaution(diabetes, exercise).
precaution(diabetes, consult_doctor).
precaution(diabetes, follow_up).
precaution(impetigo, soak_affected_area_in_warm_water).
precaution(impetigo, use_antibiotics).
precaution(impetigo, remove_scabs_with_wet_compressed_cloth).
precaution(impetigo, consult_doctor).
precaution(hypertension, meditation).
precaution(hypertension, salt_baths).
precaution(hypertension, reduce_stress).
precaution(hypertension, get_proper_sleep).
precaution(peptic_ulcer_diseae, avoid_fatty_spicy_food).
precaution(peptic_ulcer_diseae, consume_probiotic_food).
precaution(peptic_ulcer_diseae, eliminate_milk).
precaution(peptic_ulcer_diseae, limit_alcohol).
precaution(dimorphic_hemorrhoids_piles, avoid_fatty_spicy_food).
precaution(dimorphic_hemorrhoids_piles, consume_witch_hazel).
precaution(dimorphic_hemorrhoids_piles, warm_bath_with_epsom_salt).
precaution(dimorphic_hemorrhoids_piles, consume_alovera_juice).
precaution(common_cold, drink_vitamin_c_rich_drinks).
precaution(common_cold, take_vapour).
precaution(common_cold, avoid_cold_food).
precaution(common_cold, keep_fever_in_check).
precaution(chicken_pox, use_neem_in_bathing).
precaution(chicken_pox, consume_neem_leaves).
precaution(chicken_pox, take_vaccine).
precaution(chicken_pox, avoid_public_places).
precaution(cervical_spondylosis, use_heating_pad_or_cold_pack).
precaution(cervical_spondylosis, exercise).
precaution(cervical_spondylosis, take_otc_pain_reliver).
precaution(cervical_spondylosis, consult_doctor).
precaution(hyperthyroidism, eat_healthy).
precaution(hyperthyroidism, massage).
precaution(hyperthyroidism, use_lemon_balm).
precaution(hyperthyroidism, take_radioactive_iodine_treatment).
precaution(urinary_tract_infection, drink_plenty_of_water).
precaution(urinary_tract_infection, increase_vitamin_c_intake).
precaution(urinary_tract_infection, drink_cranberry_juice).
precaution(urinary_tract_infection, take_probiotics).
precaution(varicose_veins, lie_down_flat_and_raise_the_leg_high).
precaution(varicose_veins, use_oinments).
precaution(varicose_veins, use_vein_compression).
precaution(varicose_veins, dont_stand_still_for_long).
precaution(aids, avoid_open_cuts).
precaution(aids, wear_ppe_if_possible).
precaution(aids, consult_doctor).
precaution(aids, follow_up).
precaution(paralysis_brain_hemorrhage, massage).
precaution(paralysis_brain_hemorrhage, eat_healthy).
precaution(paralysis_brain_hemorrhage, exercise).
precaution(paralysis_brain_hemorrhage, consult_doctor).
precaution(typhoid, eat_high_calorie_vegitables).
precaution(typhoid, antiboitic_therapy).
precaution(typhoid, consult_doctor).
precaution(typhoid, medication).
precaution(hepatitis_b, consult_nearest_hospital).
precaution(hepatitis_b, vaccination).
precaution(hepatitis_b, eat_healthy).
precaution(hepatitis_b, medication).
precaution(fungal_infection, bath_twice).
precaution(fungal_infection, use_detol_or_neem_in_bathing_water).
precaution(fungal_infection, keep_infected_area_dry).
precaution(fungal_infection, use_clean_cloths).
precaution(hepatitis_c, consult_nearest_hospital).
precaution(hepatitis_c, vaccination).
precaution(hepatitis_c, eat_healthy).
precaution(hepatitis_c, medication).
precaution(migraine, meditation).
precaution(migraine, reduce_stress).
precaution(migraine, use_poloroid_glasses_in_sun).
precaution(migraine, consult_doctor).
precaution(bronchial_asthma, switch_to_loose_cloothing).
precaution(bronchial_asthma, take_deep_breaths).
precaution(bronchial_asthma, get_away_from_trigger).
precaution(bronchial_asthma, seek_help).
precaution(alcoholic_hepatitis, stop_alcohol_consumption).
precaution(alcoholic_hepatitis, consult_doctor).
precaution(alcoholic_hepatitis, medication).
precaution(alcoholic_hepatitis, follow_up).
precaution(jaundice, drink_plenty_of_water).
precaution(jaundice, consume_milk_thistle).
precaution(jaundice, eat_fruits_and_high_fiberous_food).
precaution(jaundice, medication).
precaution(hepatitis_e, stop_alcohol_consumption).
precaution(hepatitis_e, rest).
precaution(hepatitis_e, consult_doctor).
precaution(hepatitis_e, medication).
precaution(dengue, drink_papaya_leaf_juice).
precaution(dengue, avoid_fatty_spicy_food).
precaution(dengue, keep_mosquitos_away).
precaution(dengue, keep_hydrated).
precaution(hepatitis_d, consult_doctor).
precaution(hepatitis_d, medication).
precaution(hepatitis_d, eat_healthy).
precaution(hepatitis_d, follow_up).
precaution(heart_attack, call_ambulance).
precaution(heart_attack, chew_or_swallow_asprin).
precaution(heart_attack, keep_calm).
precaution(pneumonia, consult_doctor).
precaution(pneumonia, medication).
precaution(pneumonia, rest).
precaution(pneumonia, follow_up).
precaution(arthritis, exercise).
precaution(arthritis, use_hot_and_cold_therapy).
precaution(arthritis, try_acupuncture).
precaution(arthritis, massage).
precaution(gastroenteritis, stop_eating_solid_food_for_while).
precaution(gastroenteritis, try_taking_small_sips_of_water).
precaution(gastroenteritis, rest).
precaution(gastroenteritis, ease_back_into_eating).
precaution(tuberculosis, cover_mouth).
precaution(tuberculosis, consult_doctor).
precaution(tuberculosis, medication).
precaution(tuberculosis, rest).
precaution(stroke, call_emergency_services_immediately).
precaution(stroke, do_not_give_food_or_water).
precaution(stroke, keep_patient_calm_and_still).
precaution(stroke, note_time_of_symptom_onset).
precaution(flu, rest).
precaution(flu, drink_plenty_of_fluids).
precaution(flu, take_vitamin_c).
precaution(flu, consult_doctor).
